default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: 'pg' <%#= ENV['DB_USERNAME'] %>
  password: '1234' <%#= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: 5432

development:
  <<: *default
  database: veloshop_development

test:
  <<: *default
  database: veloshop_test
